export const pageurl = {
    HOMEPAGE: "/",
    SIGNUP: "/signup",
    CATEGORY: "/category",
    CONTACT: "/contact",
    SIGNIN: "/login",
    PRIVACYPOLICY: "/privacy-policy",
    GOVERNANCE: "/governance",
    BUSINESS: "/business",
    COOKIEPOLICY: "/cookie-policy",
    ENTERTAINMENT: "/entertainment",
    LIFESTYLE: "/lifestyles",
    FAQ: "/faq",
    DISCOVER: "/discover",
    ERROR404: "/error404",
  };