export const pageurl = {
    HOMEPAGE: "/",
    SIGNUP: "/signup",
    CATEGORY: "/category",
    CONTACTUS: "/contact",
    ABOUT: "/about",
    SPORT: "/sport",
    NEWSFEEDS: "/allnews",
    SIGNIN: "/login",
    PRIVACYPOLICY: "/privacy-policy",
    GOVERNANCE: "/governance",
    BUSINESS: "/business",
    COOKIEPOLICY: "/cookie-policy",
    ENTERTAINMENT: "/entertainment",
    SUBSCRIBE: "/subscribe",
    LIFESTYLE: "/lifestyles",
    FAQ: "/faq",
    DISCOVERAFRICA: "/africa",
    ERROR404: "/error404",
  };